name: Docker CI

on:
  schedule:
    - cron: '10 1 * * 0'
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
          - 'coqorg/coq:8.17'
          - 'coqorg/coq:8.16'
          - 'coqorg/coq:8.15'
          - 'coqorg/coq:8.14'
          - 'coqorg/coq:8.13'
          - 'coqorg/coq:8.12'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-huffman.opam'
          custom_image: ${{ matrix.image }}
          before_install: |
            startGroup "Print opam config and unpin dune"
              opam config list; opam repo list; opam list; opam pin remove dune
            endGroup


# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
